# Generated by Django 4.2.11 on 2026-03-04 14:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official name of the healthcare facility', max_length=200, verbose_name='facility name')),
                ('facility_type', models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic'), ('urgent_care', 'Urgent Care'), ('specialty_center', 'Specialty Center'), ('diagnostic_center', 'Diagnostic Center')], default='clinic', help_text='Type of healthcare facility', max_length=20, verbose_name='facility type')),
                ('address', models.TextField(help_text='Physical address of the facility', verbose_name='address')),
                ('phone_number', models.CharField(blank=True, default='', help_text='Primary contact phone number', max_length=20, verbose_name='phone number')),
                ('latitude', models.FloatField(blank=True, help_text='GPS latitude coordinate', null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='latitude')),
                ('longitude', models.FloatField(blank=True, help_text='GPS longitude coordinate', null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='longitude')),
                ('total_beds', models.IntegerField(blank=True, help_text='Total number of beds available at the facility', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total beds')),
                ('available_beds', models.IntegerField(blank=True, help_text='Number of beds currently available', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='available beds')),
                ('staff_count', models.IntegerField(blank=True, help_text='Number of medical staff on duty', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='staff count')),
                ('services_offered', models.JSONField(blank=True, default=list, help_text='List of medical services offered at the facility', verbose_name='services offered')),
                ('average_wait_time_minutes', models.IntegerField(blank=True, help_text='Average patient wait time in minutes', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='average wait time (minutes)')),
                ('ambulance_available', models.BooleanField(default=False, help_text='Whether ambulance service is available', verbose_name='ambulance available')),
                ('notification_endpoint', models.URLField(blank=True, default='', help_text='API endpoint for receiving notifications', max_length=500, null=True, verbose_name='notification endpoint')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the facility is currently operational', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'facility',
                'verbose_name_plural': 'facilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FacilityRouting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_token', models.CharField(db_index=True, help_text='Anonymous patient identifier from Triage Agent', max_length=64, verbose_name='patient token')),
                ('triage_session_id', models.CharField(blank=True, help_text='Reference to triage session', max_length=100, verbose_name='triage session ID')),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], help_text='Risk level from Triage Agent', max_length=20, verbose_name='risk level')),
                ('primary_symptom', models.CharField(help_text='Primary symptom from triage', max_length=100, verbose_name='primary symptom')),
                ('secondary_symptoms', models.JSONField(blank=True, default=list, help_text='Secondary symptoms from triage', verbose_name='secondary symptoms')),
                ('has_red_flags', models.BooleanField(default=False, help_text='Emergency red flags detected', verbose_name='has red flags')),
                ('chronic_conditions', models.JSONField(blank=True, default=list, help_text='Chronic conditions from triage', verbose_name='chronic conditions')),
                ('patient_district', models.CharField(help_text='Patient district/area', max_length=100, verbose_name='patient district')),
                ('patient_location_lat', models.FloatField(blank=True, help_text='Patient GPS latitude', null=True, verbose_name='patient latitude')),
                ('patient_location_lng', models.FloatField(blank=True, help_text='Patient GPS longitude', null=True, verbose_name='patient longitude')),
                ('booking_type', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], help_text='Whether booking is automatic or manual', max_length=20, verbose_name='booking type')),
                ('routing_status', models.CharField(choices=[('pending', 'Pending'), ('matching', 'Matching Facilities'), ('notified', 'Facility Notified'), ('confirmed', 'Confirmed by Facility'), ('rejected', 'Rejected by Facility'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='routing status')),
                ('facility_match_score', models.FloatField(blank=True, help_text='AI or rule-based matching score (0-1)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='facility match score')),
                ('distance_km', models.FloatField(blank=True, help_text='Distance to facility in kilometers', null=True, verbose_name='distance')),
                ('triage_received_at', models.DateTimeField(auto_now_add=True, help_text='When triage data was received', verbose_name='triage received at')),
                ('facility_notified_at', models.DateTimeField(blank=True, help_text='When facility was notified', null=True, verbose_name='facility notified at')),
                ('facility_confirmed_at', models.DateTimeField(blank=True, help_text='When facility confirmed booking', null=True, verbose_name='facility confirmed at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('assigned_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_routings', to='facilities.facility', verbose_name='assigned facility')),
            ],
            options={
                'verbose_name': 'facility routing',
                'verbose_name_plural': 'facility routings',
                'ordering': ['-triage_received_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_token', models.CharField(db_index=True, help_text='Anonymous patient identifier', max_length=64, unique=True, verbose_name='patient token')),
                ('preferred_channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('ussd', 'USSD'), ('email', 'Email'), ('any', 'Any')], default='whatsapp', help_text='Patient preferred notification channel', max_length=20, verbose_name='preferred channel')),
                ('phone_number', models.CharField(blank=True, help_text='Patient phone number for notifications', max_length=20, verbose_name='phone number')),
                ('email_address', models.EmailField(blank=True, help_text='Patient email address for notifications', max_length=254, verbose_name='email address')),
                ('enable_facility_updates', models.BooleanField(default=True, help_text='Receive notifications about facility responses', verbose_name='enable facility updates')),
                ('enable_appointment_reminders', models.BooleanField(default=True, help_text='Receive appointment reminders', verbose_name='enable appointment reminders')),
                ('enable_case_updates', models.BooleanField(default=True, help_text='Receive general case status updates', verbose_name='enable case updates')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start time for quiet hours (no notifications)', null=True, verbose_name='quiet hours start')),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End time for quiet hours (no notifications)', null=True, verbose_name='quiet hours end')),
                ('language_preference', models.CharField(choices=[('en', 'English'), ('sw', 'Swahili'), ('lg', 'Luganda')], default='en', help_text='Preferred notification language', max_length=10, verbose_name='language preference')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Patient Notification Preference',
                'verbose_name_plural': 'Patient Notification Preferences',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_token', models.CharField(db_index=True, help_text='Anonymous patient identifier', max_length=64, verbose_name='patient token')),
                ('triage_session_id', models.CharField(blank=True, help_text='Related triage session', max_length=64, null=True, verbose_name='triage session ID')),
                ('notification_type', models.CharField(choices=[('facility_confirmed', 'Facility Confirmed'), ('facility_rejected', 'Facility Rejected'), ('alternative_facility', 'Alternative Facility'), ('bed_reserved', 'Bed Reserved'), ('appointment_scheduled', 'Appointment Scheduled'), ('case_update', 'Case Update'), ('reminder', 'Reminder')], help_text='Type of notification', max_length=30, verbose_name='notification type')),
                ('title', models.CharField(help_text='Notification title', max_length=200, verbose_name='title')),
                ('message', models.TextField(help_text='Full notification message', verbose_name='message')),
                ('delivery_channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('ussd', 'USSD'), ('email', 'Email'), ('web', 'Web')], default='whatsapp', help_text='How the notification was sent', max_length=20, verbose_name='delivery channel')),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('read', 'Read')], default='pending', help_text='Delivery status of the notification', max_length=20, verbose_name='delivery status')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the notification was sent', null=True, verbose_name='sent at')),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When the notification was delivered', null=True, verbose_name='delivered at')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the notification was read', null=True, verbose_name='read at')),
                ('error_message', models.TextField(blank=True, help_text='Error message if delivery failed', verbose_name='error message')),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of delivery attempts', validators=[django.core.validators.MaxValueValidator(5)], verbose_name='retry count')),
                ('additional_data', models.JSONField(blank=True, default=dict, help_text='Additional notification data', verbose_name='additional data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('facility', models.ForeignKey(blank=True, help_text='Facility related to this notification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_notifications', to='facilities.facility')),
                ('routing', models.ForeignKey(help_text='Related facility routing', on_delete=django.db.models.deletion.CASCADE, related_name='patient_notifications', to='facilities.facilityrouting')),
            ],
            options={
                'verbose_name': 'Patient Notification',
                'verbose_name_plural': 'Patient Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacilityNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_case', 'New Case'), ('confirmation', 'Confirmation'), ('cancellation', 'Cancellation'), ('update', 'Update'), ('reminder', 'Reminder')], default='new_case', max_length=20)),
                ('notification_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('subject', models.CharField(help_text='Notification subject line', max_length=200)),
                ('message', models.TextField(help_text='Notification message content')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Structured payload for API notifications')),
                ('facility_response', models.JSONField(blank=True, help_text='Response data from facility', null=True)),
                ('response_received_at', models.DateTimeField(blank=True, help_text='When facility response was received', null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='When notification was acknowledged', null=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When notification was sent', null=True)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('error_message', models.TextField(blank=True, help_text='Error message if sending failed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility')),
                ('routing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='facilities.facilityrouting')),
            ],
            options={
                'verbose_name': 'facility notification',
                'verbose_name_plural': 'facility notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacilityCapacityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_beds', models.IntegerField(help_text='Total beds at time of logging', null=True)),
                ('available_beds', models.IntegerField(help_text='Available beds at time of logging', null=True)),
                ('staff_count', models.IntegerField(help_text='Staff count at time of logging', null=True)),
                ('average_wait_time', models.IntegerField(help_text='Average wait time at time of logging', null=True)),
                ('beds_change', models.IntegerField(default=0, help_text='Number of beds added/removed')),
                ('change_reason', models.CharField(blank=True, help_text='Reason for capacity change', max_length=100)),
                ('change_notes', models.TextField(blank=True, help_text='Additional notes about the change')),
                ('source', models.CharField(default='manual', help_text='Source of the capacity update', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_logs', to='facilities.facility')),
            ],
            options={
                'verbose_name': 'facility capacity log',
                'verbose_name_plural': 'facility capacity logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacilityCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(help_text='Overall match score (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('distance_km', models.FloatField(blank=True, help_text='Distance to patient in kilometers', null=True)),
                ('has_capacity', models.BooleanField(default=False, help_text='Facility has available capacity')),
                ('offers_required_service', models.BooleanField(default=False, help_text='Facility offers required services')),
                ('can_handle_emergency', models.BooleanField(default=False, help_text='Facility can handle emergency cases')),
                ('selection_reason', models.TextField(blank=True, help_text='Reason for facility selection')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility')),
                ('routing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='facilities.facilityrouting')),
            ],
            options={
                'verbose_name': 'facility candidate',
                'verbose_name_plural': 'facility candidates',
                'ordering': ['-match_score'],
            },
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['facility_type'], name='facilities__facilit_dd5426_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['is_active'], name='facilities__is_acti_a1584a_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['latitude', 'longitude'], name='facilities__latitud_c27960_idx'),
        ),
        migrations.AddIndex(
            model_name='patientnotification',
            index=models.Index(fields=['patient_token', 'created_at'], name='facilities__patient_b9fb6b_idx'),
        ),
        migrations.AddIndex(
            model_name='patientnotification',
            index=models.Index(fields=['delivery_status', 'created_at'], name='facilities__deliver_3750fc_idx'),
        ),
        migrations.AddIndex(
            model_name='patientnotification',
            index=models.Index(fields=['notification_type', 'created_at'], name='facilities__notific_b4eeaa_idx'),
        ),
        migrations.AddIndex(
            model_name='patientnotification',
            index=models.Index(fields=['routing', 'notification_type'], name='facilities__routing_b9364c_idx'),
        ),
        migrations.AddIndex(
            model_name='facilityrouting',
            index=models.Index(fields=['patient_token'], name='facilities__patient_3ca80b_idx'),
        ),
        migrations.AddIndex(
            model_name='facilityrouting',
            index=models.Index(fields=['routing_status', 'triage_received_at'], name='facilities__routing_4bbe1d_idx'),
        ),
        migrations.AddIndex(
            model_name='facilityrouting',
            index=models.Index(fields=['assigned_facility', 'routing_status'], name='facilities__assigne_e9c38b_idx'),
        ),
        migrations.AddIndex(
            model_name='facilityrouting',
            index=models.Index(fields=['risk_level', 'triage_received_at'], name='facilities__risk_le_93b099_idx'),
        ),
        migrations.AddIndex(
            model_name='facilitynotification',
            index=models.Index(fields=['facility', 'notification_status'], name='facilities__facilit_85b90e_idx'),
        ),
        migrations.AddIndex(
            model_name='facilitynotification',
            index=models.Index(fields=['routing', 'notification_type'], name='facilities__routing_abf086_idx'),
        ),
        migrations.AddIndex(
            model_name='facilitynotification',
            index=models.Index(fields=['notification_status', 'created_at'], name='facilities__notific_83b1ea_idx'),
        ),
        migrations.AddIndex(
            model_name='facilitycapacitylog',
            index=models.Index(fields=['facility', 'created_at'], name='facilities__facilit_781c1c_idx'),
        ),
        migrations.AddIndex(
            model_name='facilitycapacitylog',
            index=models.Index(fields=['change_reason'], name='facilities__change__15691c_idx'),
        ),
        migrations.AddIndex(
            model_name='facilitycapacitylog',
            index=models.Index(fields=['source'], name='facilities__source_476b0f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='facilitycandidate',
            unique_together={('routing', 'facility')},
        ),
    ]
