# Generated by Django 4.2.11 on 2026-03-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_facility_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='district',
            field=models.CharField(blank=True, default='', help_text='Administrative district where the facility is located', max_length=100, verbose_name='district'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['district'], name='facilities__distric_12ca59_idx'),
        ),
    ]
