# Generated by Django 6.0.2 on 2026-03-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_facility_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityrouting',
            name='patient_village',
            field=models.CharField(blank=True, help_text='Patient village/subcounty from triage', max_length=100, null=True, verbose_name='patient village'),
        ),
    ]
