# Generated by Django 6.0.2 on 2026-03-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VillageCoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village', models.CharField(db_index=True, max_length=100, verbose_name='village')),
                ('district', models.CharField(db_index=True, max_length=100, verbose_name='district')),
                ('latitude', models.FloatField(help_text='Cached latitude from OpenStreetMap', verbose_name='latitude')),
                ('longitude', models.FloatField(help_text='Cached longitude from OpenStreetMap', verbose_name='longitude')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When this cache entry was last updated', verbose_name='last updated')),
                ('lookup_count', models.IntegerField(default=1, help_text='Number of times this location has been looked up', verbose_name='lookup count')),
            ],
            options={
                'verbose_name': 'village coordinates',
                'verbose_name_plural': 'village coordinates',
                'indexes': [models.Index(fields=['village', 'district'], name='triage_vill_village_79ec71_idx'), models.Index(fields=['last_updated'], name='triage_vill_last_up_b72b72_idx')],
                'unique_together': {('village', 'district')},
            },
        ),
    ]
